### ISSUE TITLE
No definition of UpdateBotStatus

### ISSUE THREAD

**Issue by Enisto** [JeremyEspresso/RAGEMP-DiscordIntegration#1]
Hi
at the 1.1 .dll Visual Sudio give me the hint, that 
`

        [Command("botstatus")]
        public async void UpdateBotStatusCommand(Player player, string gameName, Discord.ActivityType eActivityType, Discord.UserStatus eUserStatus)
        {
            await Integration.DiscordIntegration.UpdateBotStatus(gameName, eActivityType, eUserStatus).ConfigureAwait(true);
        }`
as spacial UpdateBotStatus is not defined. I looked at the repo and couldn't found this function inside the VS-Solution.
![image](https://user-images.githubusercontent.com/52052024/89739522-b9bc8e80-da81-11ea-8f75-faa93bc7b255.png)

Greatings Enisto

**Comment by JeremyEspresso** [comment]
Use Integration.DiscordIntegration.UpdateStatus instead. I changed names of the method. I will update the example script tomorrow
