### ISSUE TITLE
Just comment

### ISSUE THREAD

**Issue by Mippoose** [JeremyEspresso/RAGEMP-DiscordIntegration#3]
Hi, ur script is just rly usefull! Ty so much for it. But it should be better to make some change in it. I think it will be easier to configure if u'll create an event for "message recieve". Cause not everyone will use only messaging. 
Sry for my eng, but i'm just wanna tell that it should be better to get event with channel id and message, and after that work with it in some void. 
F.E
[DiscordEvent.MessageReceived]
public static void BlaBla(ulong channelID, string msg)
{
// work with it
}
I'll wait for ur reply and comment. Ty again ^_^

**Comment by JeremyEspresso** [comment]
I understand what you are saying. I will probably do that coming weekend. Thanks for the suggestion.

**Comment by Mippoose** [comment]
Yeah. Now I have another problem with ur script. I'm trying to add ur source code to my own discord management system. When I'm trying to run server I get the error.
![image](https://user-images.githubusercontent.com/32161075/91023855-e7c0d780-e618-11ea-8021-f66d9d770d3a.png)
