### ISSUE TITLE
0.3.7 not working!!!

### ISSUE THREAD

**Issue by rzn1** [JeremyEspresso/RAGEMP-DiscordIntegration#4]
I did everything but im still getting that error

Exception message: Unable to load one or more of the requested types.
Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

I have system threading tasks in my runtime folder. Its 4.3.0 version. 
I tried everything on 1.1 server and it was working great however i need it on 0.3.7...!!!

**Comment by rzn1** [comment]
If i replace 0.3.7 system.threading.tasks with 1.1 system.threading.tasks that error fixes but then im getting same thing with netstandard this time and if i replace that also my server just crashes instantly..!!

**Comment by rzn1** [comment]
I guess its asking for System.Threading.Tasks, Version=4.1.2.0 and mine is 4.3.0!

**Comment by rzn1** [comment]
https://gyazo.com/92b4959d9ddaa22465ffe39015e19f9d

**Comment by rzn1** [comment]
And just like with netstandard its asking for 2.1.0.0 and mine is 2.0.0.0 https://gyazo.com/e3e90d6a05a9866b69ed6c98f29a6639

**Comment by JeremyEspresso** [comment]
You need to use a .NET Core 3.1 project, not net standard

**Comment by JeremyEspresso** [comment]
And compile it into a class library

**Comment by rzn1** [comment]
Yes it is .net core 3.1....

**Comment by rzn1** [comment]
As i told i tried it on 1.1 server version and it was working. But on my main 0.3.7 it is not

**Comment by JeremyEspresso** [comment]
Did you use the 0.3.7 files/branch?

**Comment by rzn1** [comment]
for 1.1 i used 1.1 and for 0.3.7 server 0.3.7 files ofc.

**Comment by JeremyEspresso** [comment]
Just copy paste the class from the Integration namespace into your own script and install the needed nugets and place those in your runtime

**Comment by rzn1** [comment]
https://media.giphy.com/media/l4JA1COQqiZB6/giphy.gif

**Comment by rzn1** [comment]
Idk i have tried everything it is just not starting on 0.3.7 and i've seen its not only me that has problems with this on 0.3.7 version..

**Comment by JeremyEspresso** [comment]
invalid
