### ISSUE TITLE
0.3.7 issue with wrong files tipo

### ISSUE THREAD

**Issue by dkay9999** [JeremyEspresso/RAGEMP-DiscordIntegration#5]
my runtime .dll files is wrong version and resource is asking for other versions.

can you send me your 0.3.7 files?

**Comment by white-hackers** [comment]
Just install them in your Visual studio

Просто установите их в вашем Visual studio

**Comment by dkay9999** [comment]
ITS WORKING FOR 1.1 BUT NOT FOR 0.3.7 I KNOW HOW TO INSTALL IT

ERROR I GET IS = Could not load file or assembly 'System.Threading.Tasks, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

BUT MY VERSION IS 4.3.0

**Comment by JeremyEspresso** [comment]
I am currently working on a new version of this resource that includes event attributes for the discord events. 

For your issue I recommend cloning this repository and taking the script I wrote and add it to the server as it is. Also make sure to place the discord dependencies inside your runtime folder.

Good luck

**Comment by dkay9999** [comment]
yes but what i am saying it works perfectly fine on rage 1.1 but on 0.3.7 it says wrong version

**Comment by dkay9999** [comment]
could you give me ur discord please?

**Comment by JeremyEspresso** [comment]
Jer#0002
