### ISSUE TITLE
How to register a discordChannelID channel

### ISSUE THREAD

**Issue by white-hackers** [JeremyEspresso/RAGEMP-DiscordIntegration#6]
How to register a discordChannelID channel when starting the server and not when entering a command in the "registerchannel"chat. Every restart of the server, you need to write a command to the chat "registerchannel" to register the channel on the server, how to make the channel register automatically?

    [Command("registerchannel")]
    public void RegisterDiscord(Player player, ulong discordChannelID)
    {
        bool bSuccess = Integration.DiscordIntegration.RegisterChannelForListenting(discordChannelID);

        player.SendChatMessage(bSuccess ? "Подключено" : "Не подключено");
    }

**Comment by JeremyEspresso** [comment]
you can make it register a channel in the constructor of a class that gets initialized on startup. Or you could change the Command attribute to the ResourceStart attribute.
